framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            query.bus: null
        transports:
            sync: '%env(MESSENGER_TRANSPORT_SYNC_DSN)%'
            async: '%env(MESSENGER_TRANSPORT_ASYNC_DSN)%'
        routing:
            'App\Shared\Domain\Query': sync
