services:
    app:
        build:
            context: .
            target: fpm-dev
        volumes:
            - ./:/usr/app:cached
        depends_on:
            - database
        environment:
            - XDEBUG_CONFIG

    nginx:
        image: nginx:1.21
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./etc/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .certs:/usr/app/.certs:ro,cached
            - ./public:/usr/app/public:ro,cached
        depends_on:
            - app

    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
