git_healthcheck_rest:
    resource: ../../src/Git/Healthcheck/Infrastructure/Rest/
    type: annotation

git_pull-request_rest:
    resource: ../../src/Git/PullRequest/Infrastructure/Rest/
    type: annotation
