healthcheck_controllers:
    resource: ../../src/Example/Healthcheck/Infrastructure/Controller/
    type: annotation

test_controllers:
    resource: ../../src/Example/Test/Infrastructure/Controller/
    type: annotation

shared_controllers:
    resource: ../../src/Shared/Infrastructure/Controller/
    type: annotation
