parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Shared\Domain\CommandHandler:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Shared\Domain\QueryHandler:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    App\:
        resource: '../src/'
        exclude:
            - '../src/Git/PullRequest/Domain/Entity/'
            - '../src/Shared/Domain/Entity/'
            - '../src/Kernel.php'

    App\Git\PullRequest\Infrastructure\Rest\:
        resource: ../src/Git/PullRequest/Infrastructure/Rest
        public: true
